### ISSUE TITLE
Design decisions: threading

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_ethercat_drivers#2]
With the first control loop closed it seems the right time to review the current status and to make a number of design decisions explicit. I'll open the discussion in this issue. 

Threads. Currently, the 'caller' instantiating the [EtherCat interface](https://github.com/tue-robotics/ethercat_interface) controls the (at this moment only one) thread. This is also advocated by @reinzor . The main advantages:
* The caller has control over everything that happens; no magic, nothing on the background
* No threading issues. An update loop in a separate thread needs to be designed carefully so that, e.g., a write action cannot write in a data location that is at the same time copied to the ethercat_out struct. N.B., using threading locks is also undesired looking with performance in mind.
However, there's still quite a lot missing:
* PDO and statethreads (mentioned by @Timple )
* Serial communication (e.g., RS485 in EL6022 or TUEes030)
Furthermore, running the main thread at a low frequency may also cause trouble:
* (correct me if I'm wrong) the EtherCAT protocol expects a minimum update rate
* encoder overflow isn't handled correctly.

This raises the questions:
* Do we want to keep the caller responsible for calling the `sendAll` and `receiveAll` functions at a suitable rate?
* Should PDO and state stuff be handled in separate threads?
* How are we going to implement serial communication?

@MaxBaeten @alberth I guess you will probably also have an opinion on this.

**Comment by Rayman** [comment]
Seems like a lot of advantages. If we can avoid threads, we should.

**Comment by alberth** [comment]
I agree, less threads is better. They're difficult to code and understand, and quite non-debuggable due to timing issues.

However, it would seem that you do need regular calls to keep the hardware operating smoothly here. I haven't read the EtherCaT protocol, but I suspect it's the devices that set minimum rate. In my simple tests a digital IO board had no problems with 1Hz or less, while the E/Box needs at least around 20Hz.
The RS485 interface has a 20-ish character buffer, at 38.4Kb/s iirc, so that's at least one regular call to perform. Encoders are another.

I don't know exactly what statethreads are, but if it's just avoiding inversion of control (https://martinfowler.com/bliki/InversionOfControl.html) I am not convinced it needs a thread. There exist quite simple ways to invert control flow of a function (essentially turning it into a sequence of callbacks), or you can use a state machine (which is the same thing, just in a different shape).
No idea what PDO does to warrant its own thread, so can't comment on that.

The first question thus seems whether it is feasible to keep everything in one thread. It needs to loop regularly at all times, so it may not block (other than waiting to start the next loop), and must do everything that needs to be done in that single thread. If "yes" is the answer, that's the simplest solution.

Otherwise, you have at least two threads. Locking is needed (although perhaps some things can be done with `std::atomic` variables). As long as locking is sufficiently fine grained (don't lock out all access if you generally need only a small part) and minimized (do minimal work while you have a lock, eg swap a pointer rather than copy data), locking is not a problem in itself.

**Comment by MCFurry** [comment]
Hey guys, Ferry here. 
@Timple pointed me at this discussion so I'll try to contribute from my experience/knowledge.

I can imagine avoiding threads as much as possible is preferable, but as mentioned before, EtherCAT slaves have a watchdog which times out if no PDO has been received within a certain amount of time which causes them to go into SAFEOP mode. This you want to avoid since you'll have to put them into OP-mode again before you can continue working with them. Therefore I would strongly advice to at least put pdo transfer/receive in a separate thread. This thread is very lightweight and can be set to higher priority to make sure pdo transfers happen on time.

The state check is optional as it simply checks whether all slaves are still operational and no network errors occured. It is preferred to do of course but there are no timing requirements to this.

In the ROS repo ethercat_soem, there is the ebox.c example which shows a minimal setup like this as an example.

**Comment by Rayman** [comment]
We'll call `ethercat_interface` at a regular interval (~1000Hz) so a regular PDO will happen.

**Comment by MCFurry** [comment]
That's okay, but remember that if another piece of software requires a CPU burst and the PDO does not have more priority, it may be delayed too much.

Furthermore, if you have closed loop control over EtherCAT and you designed your controller at 1KHz sample rate, but the actual samples won't be timed nicely at this 1KHz, there is no guarantee for stability anymore!
