### ISSUE TITLE
Design decisions: data types

### ISSUE THREAD

**Issue by jlunenburg** [tue-robotics/tue_ethercat_drivers#3]
The [EtherCat interface](https://github.com/tue-robotics/ethercat_interface) now exposes 'ReadInterface' and 'WriteInterface' objects. The ReadInterface always returns a double (also if reading a digital in or, e.g., an encoder that basically represents an integer value). Similarly, the WriteInterface always takes a double as argument.

Although this is easy in a way (you never have to think about the datatype) it's also a bit of abuse of a C++: one of the purposes of typing a language is avoiding bugs...

IMHO it would be nicer to make a distinction between these...

@reinzor @Timple @alberth @MaxBaeten what's your opinion?

**Comment by alberth** [comment]
Conversion to `double` seems a strange choice to me. Doing the conversion here has no advantage for signals that eventually become a floating point value, the conversion must be reverted if you ever want to access the signal as integer or as a collection of bits, and it restricts values to 53 of the 64 bits (assuming the IEEE double precision representation). If you want a single data type I'd suggest to use `std::int64_t` instead. It's close to how EtherCaT talks, you can transport 64 bits of data, and it eliminates unnecessary conversions in case of integer data (unsigned 64 bit values need a static cast but that has no performance cost, since it literally has the same bit representation, unlike doubles vs integers).

---

As for your real question, the advantage of a single data type is that you can store lots of signals in a single `map<size_t, interface>` variable, talk in magic numbers, and get all interfaces from a single function. (That is, you can talk and think in "a signal in general" without caring what it is.)
It's a simple solution to get the EtherCaT signals available.

The disadvantage I think is that it leaks hardware knowledge. Eventually "everything is a general signal" is not going to work, at some point a conversion to a sane SI unit like m/s or Newtons is required, and you need hardware details for that. By not doing the conversion here, it needs to be done at a higher level, which implies it has to know about hardware details which may or may not be a bad idea.

The alternative is to consider each signal as unique, and give it its own variable (or object, where you can handle eg conversion as well). Higher levels then access this variable.

If ROS control gives directions here, I'd follow that. Otherwise, I would likely do the latter, as conversion, and considering signals as unique must be done at some point anyway as far as I can see, and hardware knowledge should stay close to hardware access.
